spring.datasource:
  url: jdbc:mysql://${endpoint}/beekeeper?useSSL=false
  username: ${username}
properties:
  apiary.queue-url: ${queue}
graphite:
  enabled: ${graphite-enabled}
  host: ${graphite-host}
  prefix: ${graphite-prefix}
  port: ${graphite-port}
