name: Terraform Validation

on: [push]

jobs:
  test:
    name: Verify Terraform is valid
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        terraform_dir: [main, lambda]

    steps:
      - uses: actions/checkout@v1
      - working-directory: ${{ matrix.terraform_dir }}
      - name: "Terraform Init"
        run: terraform init
      - name: "Validate Terraform"
        run: terraform validate
