name: Terraform Validation

on: [ push, pull_request ]

jobs:
  test:
    name: Verify Terraform is valid for ${{ matrix.terraform_dir }}
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    container:
      image: hashicorp/terraform:0.12.29
    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - uses: actions/checkout@v1
      - name: "Terraform Init"
        run: terraform init
      - name: "Validate Terraform"
        run: terraform validate
